# Generated by Django 4.2.5 on 2023-11-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifome2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanche',
            name='preçodoproduto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
