# Generated by Django 4.2.5 on 2023-11-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifome2', '0002_lanche_preçodoproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanche',
            name='curso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lanche',
            name='nome_vendedor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lanche',
            name='produto_oferecido',
            field=models.CharField(max_length=100),
        ),
    ]
