# Generated by Django 4.2.5 on 2023-12-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifome2', '0003_alter_lanche_curso_alter_lanche_nome_vendedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanche',
            name='curso',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lanche',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='lanche',
            name='nome_vendedor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lanche',
            name='produto_oferecido',
            field=models.CharField(max_length=255),
        ),
    ]
