# Generated by Django 5.0.7 on 2024-09-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifome2', '0004_alter_lanche_curso_alter_lanche_foto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('curso', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
